[package]
name = "aimarekin/instancer"
description = "Programatically create instances. Inspired by Fusion, specifically for use with UI."
license = "MIT"
authors = ["Aimarekin"]
version = "0.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
